#!/usr/bin/env python3
"""Generates NUMBERS.md from results/*.jsonl. Usage: python3 bench/ledger.py [results_dir] [out_file]

Every figure in NUMBERS.md comes from a row in results/, and each section names its file.
When an experiment was repeated, the table shows the median with the range in brackets.
"""
import json
import os
import statistics
import sys
from collections import defaultdict

RES = sys.argv[1] if len(sys.argv) > 1 else "results"
OUT = sys.argv[2] if len(sys.argv) > 2 else "NUMBERS.md"

NAME = {"metricsdb": "MetricsDB", "vm": "VictoriaMetrics", "victoriametrics": "VictoriaMetrics",
        "influx": "InfluxDB", "influxdb": "InfluxDB", "metricsdb-cluster": "MetricsDB, 3 nodes, RF=2",
        "metricsdb-3-nodes-rf2": "MetricsDB, 3 nodes, RF=2 (first 2M lines)", "metricsdb-fsync-off": "MetricsDB, WAL fsync off"}
TYPES = ["single-groupby-1-1-1", "single-groupby-1-1-12", "single-groupby-1-8-1", "single-groupby-5-1-1",
         "single-groupby-5-1-12", "single-groupby-5-8-1", "cpu-max-all-1", "cpu-max-all-8",
         "double-groupby-1", "double-groupby-5", "double-groupby-all"]


def rows(name):
    p = os.path.join(RES, name)
    if not os.path.exists(p):
        return []
    return [json.loads(l) for l in open(p) if l.strip()]


def med(xs, fmt="{:,.0f}"):
    xs = [x for x in xs if x is not None]
    if not xs:
        return "n/a"
    m = statistics.median(xs)
    if len(xs) == 1 or min(xs) == max(xs):
        return fmt.format(m)
    return f"{fmt.format(m)} [{fmt.format(min(xs))} to {fmt.format(max(xs))}]"


def load_range(rs):
    hc = [r.get("host_cpu_pct_before") for r in rs if r.get("host_cpu_pct_before") is not None]
    wl = [r.get("load_after", {}).get("wsl_load1") for r in rs if r.get("load_after")]
    parts = []
    if hc:
        parts.append(f"Windows host CPU before the run {min(hc):.0f}% to {max(hc):.0f}%")
    if wl:
        parts.append(f"WSL 1-minute load after {min(wl):.1f} to {max(wl):.1f}")
    return "; ".join(parts) if parts else "load not recorded"


out = []
w = out.append
w("# NUMBERS")
w("")
w("Every figure MetricsDB reports, generated by `bench/ledger.py` from `results/*.jsonl`. Each section names "
  "the file its rows come from. Where an experiment was repeated, cells show the median with the range in brackets.")
w("")
w("**Machine.** One mini PC: AMD Ryzen 3 4300U (4 cores), 16 GB, Windows 11 with WSL2 (Ubuntu 24.04, 2 vCPU and "
  "6 GB given to the VM). The database under test, the load generator and the query client all run inside that "
  "VM. VictoriaMetrics and InfluxDB run in Docker in the same VM with their default settings, one database at a "
  "time. The box is shared with other jobs, so each row records the host CPU and WSL load next to it. "
  "**Data:** the standard benchmark (TSBS) DevOps use case, 100 hosts, 24 hours at 10-second intervals: "
  "7,776,000 lines, 87,264,000 samples. Generated by the benchmark, not production traffic.")
w("")

# ---------------------------------------------------------------- M0
m0 = rows("m0_tsbs_baseline.jsonl")
if m0:
    w("## M0: the benchmark's own loader against VictoriaMetrics (`results/m0_tsbs_baseline.jsonl`)")
    w("")
    for r in m0:
        w(f"- {r['ts']}: `{r['tool']}`, {r['workers']} workers, batch {r['batch_size']}: {r['tsbs_summary'].strip()} "
          f"(target {r['target']}, {r.get('version', '')}).")
    w("")

# ---------------------------------------------------------------- exp1
e1 = [r for r in rows("exp1.jsonl") if not r.get("label", "").startswith("prelim")]
if e1:
    w("## exp1: bytes per sample on disk (`results/exp1.jsonl`)")
    w("")
    w("After loading the whole benchmark day and each database's own flush (MetricsDB: `/admin/flush`, which cuts "
      "the head into blocks and compacts; VictoriaMetrics: `force_flush` and `force_merge`, then 60 s; InfluxDB: "
      "120 s idle with default compaction). Bytes are the whole data directory. Uncompressed is 16 bytes "
      "(8-byte timestamp, 8-byte float).")
    w("")
    w("| database | runs | bytes on disk | bytes per sample | x smaller than 16 B |")
    w("|---|---|---|---|---|")
    by = defaultdict(list)
    for r in e1:
        by[r.get("label", r["db"])].append(r)
    for db, rs in by.items():
        bps = [r["bytes_per_sample"] for r in rs]
        w(f"| {NAME.get(db, db)} | {len(rs)} | {med([r['bytes_on_disk'] for r in rs])} | {med(bps, '{:.3f}')} | "
          f"{med([16 / b for b in bps], '{:.1f}')} |")
    w("")
    mdb = [r for r in e1 if r["db"] == "metricsdb"]
    if mdb and "detail" in mdb[-1]:
        w(f"MetricsDB breakdown (last run): `{mdb[-1]['detail'][:600]}`")
        w("")

# ---------------------------------------------------------------- exp2
e2 = [r for r in rows("exp2.jsonl") if not r.get("label", "").startswith("prelim")]
if e2:
    w("## exp2: ingest (`results/exp2.jsonl`)")
    w("")
    w("The same loader (`bench load`) replays the same line-protocol file into each database's `/write`, "
      "4 concurrent writers, 1,000 lines (about 11,200 samples) per request. Latency is per request, from send to "
      "acknowledgement; MetricsDB acknowledges only after the WAL fsync.")
    w("")
    w("| database | runs | samples | samples/s | batch p50 ms | batch p99 ms | batch max ms | retries | load |")
    w("|---|---|---|---|---|---|---|---|---|")
    by = defaultdict(list)
    for r in e2:
        by[r.get("label", r["db"])].append(r)
    for db, rs in by.items():
        L = [r["batch_latency_ms"] for r in rs]
        w(f"| {NAME.get(db, db)} | {len(rs)} | {med([r['samples'] for r in rs])} | {med([r['samples_per_s'] for r in rs])} | "
          f"{med([l['p50'] for l in L], '{:.0f}')} | {med([l['p99'] for l in L], '{:.0f}')} | {med([l['max'] for l in L], '{:.0f}')} | "
          f"{sum(r['retries'] for r in rs)} | {load_range(rs)} |")
    w("")

# ---------------------------------------------------------------- exp3
e3 = rows("exp3.jsonl")
if e3:
    w("## exp3: latency per benchmark query type (`results/exp3.jsonl`)")
    w("")
    w("100 queries per type generated by `tsbs_generate_queries` (PromQL for MetricsDB and VictoriaMetrics, "
      "InfluxQL for InfluxDB, same hosts and time windows). The first 20 of each type warm up the database and are "
      "not measured; the other 80 run one at a time. Milliseconds, client side.")
    w("")
    dbs = [d for d in ["metricsdb", "victoriametrics", "influxdb"] if any(r["db"] == d for r in e3)]
    w("| query type | " + " | ".join(f"{NAME[d]} p50 | {NAME[d]} p99" for d in dbs) + " | MetricsDB p50 vs VictoriaMetrics |")
    w("|---|" + "---|---|" * len(dbs) + "---|")
    by = defaultdict(list)
    for r in e3:
        by[(r["db"], r["query_type"])].append(r)
    for t in TYPES:
        cells = []
        p50 = {}
        for d in dbs:
            rs = by.get((d, t), [])
            p50[d] = statistics.median([r["latency_ms"]["p50"] for r in rs]) if rs else None
            cells.append(med([r["latency_ms"].get("p50") for r in rs], "{:.1f}"))
            cells.append(med([r["latency_ms"].get("p99") for r in rs], "{:.1f}"))
        rel = ""
        if p50.get("metricsdb") and p50.get("victoriametrics"):
            ratio = p50["metricsdb"] / p50["victoriametrics"]
            rel = f"{ratio:.2f}x" + (" (MetricsDB faster)" if ratio < 1 else " (MetricsDB slower)")
        w(f"| {t} | " + " | ".join(cells) + f" | {rel} |")
    errs = sum(r.get("errors", 0) for r in e3)
    w("")
    w(f"Query errors across all runs: {errs}. {load_range(e3)}.")
    w("")

# ---------------------------------------------------------------- exp4
e4 = rows("exp4.jsonl")
if e4:
    w("## exp4: answers compared with VictoriaMetrics (`results/exp4.jsonl`)")
    w("")
    w("Every query of every type sent to both databases loaded with the same data; the answers must have the same "
      "series, the same timestamps and values equal within 1e-9 relative.")
    w("")
    w("| query type | queries | mismatched | series compared | points compared |")
    w("|---|---|---|---|---|")
    last_ts = max(r["ts"] for r in e4 if r["query_type"] == "ALL")
    batch = [r for r in e4 if r["ts"] <= last_ts]
    seen = {}
    for r in batch:
        seen[r["query_type"]] = r
    for t in TYPES + ["ALL"]:
        if t in seen:
            r = seen[t]
            w(f"| {t} | {r['queries']} | {r['mismatched_queries']} | {r['series_compared']:,} | {r['points_compared']:,} |")
    w("")

# ---------------------------------------------------------------- exp5
e5 = rows("exp5.jsonl")
if e5:
    w("## exp5: a storage node killed mid-write (`results/exp5.jsonl`, timeline in `results/exp5_timeline.jsonl`)")
    w("")
    w("3 storage nodes and a router, each its own JVM. 1,000 series, one sample each every 100 ms of wall time "
      "(10,000 samples/s offered) through the router. Node n1 gets SIGKILL at 20 s and is restarted at 40 s; the "
      "run ends at 60 s. A client that gets an error keeps the batch and retries it, as Prometheus would. A probe "
      "query every 250 ms counts the series it can see. Afterwards hints drain, anti-entropy runs twice, and every "
      "acknowledged sample is checked bit for bit through the router and on each of its replicas.")
    w("")
    w("| run | samples acked | lost | writes refused on first try | queries during outage: complete / partial / error | fewest series visible | replicas missing samples before repair | after repair | repair: ranges mismatched, samples written |")
    w("|---|---|---|---|---|---|---|---|---|")
    for r in e5:
        ps = r["probe_summary"]
        before = sum(x["missing"] for x in r["replicas_before_repair"])
        after = sum(x["missing"] for x in r["replicas_after_repair"])
        rp = r["repair_pass_1"]
        w(f"| {r['label']} | {r['samples_acked']:,} | {r['samples_lost']} | {r['ticks_failed_first_try']} of {r['ticks_sent']} ticks | "
          f"{ps['complete_during_outage']} / {ps['partial_during_outage']} / {ps['error_during_outage']} | "
          f"{ps['min_visible_series_during_outage']} of {r['series']} | {before:,} | {after:,} | "
          f"{rp.get('rangesMismatched')}, {rp.get('samplesWritten'):,} |")
    w("")

# ---------------------------------------------------------------- ooo
oo = rows("ooo.jsonl")
if oo:
    w("## Late samples (`results/ooo.jsonl`)")
    w("")
    w("500 series, one sample every 10 s for an hour; 10% of samples delivered late by a random delay. The harness "
      "simulates the acceptance rule to know which samples must be stored and which refused, then reads everything back.")
    w("")
    w("| run | window | max delay | samples | late | must store | stored | lost inside the window | refused (expected / counted by the node) | stored but should have been refused |")
    w("|---|---|---|---|---|---|---|---|---|---|")
    for r in oo:
        w(f"| {r['label']} | {r['window_ms'] // 1000} s | {r['max_delay_ms'] // 1000} s | {r['samples_sent']:,} | {r['late_samples']:,} | "
          f"{r['expected_stored']:,} | {r['stored']:,} | {r['lost_inside_window']} | {r['expected_refused']:,} / {r['db_refused_too_old']:,} | "
          f"{r['stored_but_should_be_refused']} |")
    w("")

# ---------------------------------------------------------------- faults
fl = rows("faults.jsonl")
if fl:
    w("## Fault injection (`results/faults.jsonl`)")
    w("")
    w("3 storage nodes at RF=2 under a steady write load; a nemesis, one node at a time, kills a node with SIGKILL "
      "and restarts it, freezes it with SIGSTOP, or drops its link to the router (a TCP proxy that resets the "
      "connection), each for 1.5 to 5.5 s. Then all faults heal, hints drain, anti-entropy runs, and the checker "
      "reads every acknowledged sample through the router and on both replicas.")
    w("")
    w("| run | seed | faults (kill / pause / partition) | samples acked | lost | replica samples missing after repair | ok |")
    w("|---|---|---|---|---|---|---|")
    for r in fl:
        kinds = defaultdict(int)
        for e in r["events"]:
            kinds[e["fault"]] += 1
        w(f"| {r['run']} | {r['seed']} | {kinds['kill']} / {kinds['pause']} / {kinds['partition']} | {r['samples_acked']:,} | "
          f"{r['lost_via_router']} | {r['replica_samples_missing_after_repair']} | {r['ok']} |")
    w("")

# ---------------------------------------------------------------- jmh
jm = [(f, rows(f)) for f in sorted(os.listdir(RES)) if f.startswith("jmh-") and f.endswith(".jsonl")] if os.path.isdir(RES) else []
if jm:
    w("## Microbenchmarks (JMH, `results/jmh-*.jsonl`)")
    w("")
    w("| benchmark | params | score | unit | file |")
    w("|---|---|---|---|---|")
    for f, rs in jm:
        for r in rs:
            params = ", ".join(f"{k}={v}" for k, v in (r.get("params") or {}).items())
            w(f"| {r['benchmark']} | {params} | {r['score']:.2f} ± {r.get('error', 0):.2f} | {r['unit']} | `{f}` |")
    w("")

# ---------------------------------------------------------------- other
for name, title in [("rollups.jsonl", "Rollups for long ranges"), ("query_protection.jsonl", "Query protection")]:
    rs = rows(name)
    if rs:
        w(f"## {title} (`results/{name}`)")
        w("")
        for r in rs:
            w("- " + ", ".join(f"{k}: {v}" for k, v in r.items() if k not in ("machine",)))
        w("")

open(OUT, "w").write("\n".join(out) + "\n")
print("wrote", OUT, len(out), "lines")
